name: Stats-Analysis CI
on: [ push, pull_request ]

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: PHPStan
        uses: docker://oskarstark/phpstan-ga
        with:
          args: analyse -c phpstan.neon
        env:
          REQUIRE_DEV: true
          CHECK_PLATFORM_REQUIREMENTS: false